config/routes.rb
Landlorder::Application.routes.draw do
  resources :users, :only => [:index, :show] do
    member do
      get 'venues'
    end
  end

  get  "landlord/index", :as => :dashboard
  get  "landlord/portfolio", :as => :portfolio
  get  "landlord/activity", :as => :activity
  post "landlord/sell/:id" => "landlord#sell", :as => :sell

  get  "account/index"
  get  "account/update"

  resources :venues do
    member do
      post 'buy'
    end
  end

  get "/account" => "account#index", :as => :account
  post "/account/update" => "account#update", :as => :update_account

  get "/welcome" => "sessions#welcome", :as => 'welcome'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'venues#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base

  attr_accessible :cat_color, :cat_id, :cat_image, :cat_name, :expected_profit, :expected_rent, 
                  :fsq_id, :market_value, :name, :venuid, :daily_costs

  belongs_to :user

  before_create :fetch_landlord_data, :remove_old

  def remove_old
    Venue.delete_all(["fsq_id = ? AND user_id = ?" , self.fsq_id, self.user.id])
    #Venue.delete_all(["fsq_id = ?" , self.fsq_id])
  end

  def buy

    response = LandlordRequest.post(
      "https://www.landlordgame.com/v2-1-0/buyVenue.php" ,
      {
      "auth" => self.user.ll_auth,
      "userId" => self.user.ll_user_id,
      "venueId" => self.venuid
      }
    )

    json = JSON.parse(response.body)
  end

  def fetch_landlord_data

    response = LandlordRequest.post(
      "https://www.landlordgame.com/v2-1-0/postCheckin.php" ,
      {
        "auth" => self.user.ll_auth,
        "userId" => self.user.ll_user_id,
        "venueId" => self.fsq_id
      }
    )

    json = JSON.parse(response.body)
    logger.debug json
    self.name = json['venueName']
    self.market_value = json['marketValue'].gsub(/[^0-9]/i, '').to_i
    self.venuid = json['venueId']
    self.expected_profit = json['expectedProfit'].gsub(/[^0-9]/i, '').to_i
    self.expected_rent = json['expectedRent'].gsub(/[^0-9]/i, '').to_i
    self.daily_costs = json['dailyCosts'].gsub(/[^0-9]/i, '').to_i
    self.cat_name = json['categoryInfo']['name']
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :logged_in?
  # GET /venues
  # GET /venues.json
  def index
    @venues = current_user.venues.order('created_at DESC')
    @title = "Your venues"
    @venue =Venue.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.json
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(params[:venue])
    @venue.user = current_user

    respond_to do |format|
      if @venue.save
        format.html { redirect_to venues_path, notice: 'Venue was successfully created.' }
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  def buy
    @venue = Venue.find(params[:id])
    respond_to do |format|
      msg = @venue.buy
      format.html { redirect_to venues_path, notice: "Msg : #{msg}" }
    end
  end

  # PUT /venues/1
  # PUT /venues/1.json
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :venuid %><br />
    <%= f.text_field :venuid %>
  </div>
  <div class="field">
    <%= f.label :market_value %><br />
    <%= f.number_field :market_value %>
  </div>
  <div class="field">
    <%= f.label :expected_profit %><br />
    <%= f.number_field :expected_profit %>
  </div>
  <div class="field">
    <%= f.label :expected_rent %><br />
    <%= f.number_field :expected_rent %>
  </div>
  <div class="field">
    <%= f.label :cat_id %><br />
    <%= f.text_field :cat_id %>
  </div>
  <div class="field">
    <%= f.label :cat_name %><br />
    <%= f.text_field :cat_name %>
  </div>
  <div class="field">
    <%= f.label :cat_color %><br />
    <%= f.text_field :cat_color %>
  </div>
  <div class="field">
    <%= f.label :cat_image %><br />
    <%= f.text_field :cat_image %>
  </div>
  <div class="field">
    <%= f.label :fsq_id %><br />
    <%= f.text_field :fsq_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<div class="row">
	<div class="span12">

<h3><%= @title -%></h3>
<% unless @hide_form %>
<%= form_for(@venue, :html => {:class => 'form-inline'}) do |f| %>
  <div class="input-append">
    <%= f.text_field :fsq_id, :placeholder => "Enter a foursquare id" %> <%= f.submit "Add venue", :class => 'btn' %>
  </div>
<% end %>
<% end %>


<table class="footable">
	<thead>
  <tr>
    <th data-class="expand">Name</th>
<!--     <th>Venuid</th> -->
    <th>Market value</th>
<!--     <th>Expected profit</th> -->
    <th data-hide="phone,tablet">Expected rent</th>
    <th data-hide="phone,tablet">Daily costs</th>
<!--     <th>Cat</th> -->
    <th data-hide="phone,tablet">Cat</th>
<!--     <th>Cat color</th>
    <th>Cat image</th> -->
<!--     <th data-hide="tablet"></th> -->
    <th></th>
   </tr>
</thead>
<tbody>
<% @venues.each do |venue| %>
  <tr id="tr<%= venue.id -%>">
    <td><%= link_to venue.name, venue %></td>
<!--     <td><%= venue.venuid %></td> -->
    <td><%= df venue.market_value %></td>
<!--     <td><%= df venue.expected_profit %></td> -->
    <td><%= df venue.expected_rent %></td>
    <td><%= df venue.daily_costs %></td>
<!--     <td><%= venue.cat_id %></td> -->
    <td><%= venue.cat_name %></td>
<!--     <td><%= venue.cat_color %></td>
    <td><%= venue.cat_image %></td> -->
    <!-- <td><%= link_to 'Show', venue %></td> -->
    <!-- <td><%= link_to 'Edit', edit_venue_path(venue) %></td> -->
<!--     <td><%= time_ago_in_words(venue.created_at) -%></td> -->
    <td>
    	<%= link_to raw("<i class='icon-th-large'></i>"), "https://fr.foursquare.com/v/#{venue.fsq_id}" %>
    	<% unless @hide_form %>
    	<%= link_to raw("<i class='icon-remove'></i>"), venue, method: :delete, :remote => true %>
    	<%= link_to raw("<i class='icon-shopping-cart'></i>"), buy_venue_path(venue), :method => :post %>
    	<% end %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

</div>
</div>

app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @venue.name %>
</p>

<p>
  <b>Venuid:</b>
  <%= @venue.venuid %>
</p>

<p>
  <b>Market value:</b>
  <%= @venue.market_value %>
</p>

<p>
  <b>Expected profit:</b>
  <%= @venue.expected_profit %>
</p>

<p>
  <b>Expected rent:</b>
  <%= @venue.expected_rent %>
</p>

<p>
  <b>Cat:</b>
  <%= @venue.cat_id %>
</p>

<p>
  <b>Cat name:</b>
  <%= @venue.cat_name %>
</p>

<p>
  <b>Cat color:</b>
  <%= @venue.cat_color %>
</p>

<p>
  <b>Cat image:</b>
  <%= @venue.cat_image %>
</p>

<p>
  <b>Fsq:</b>
  <%= @venue.fsq_id %>
</p>


<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>