config/routes.rb
Landlorder::Application.routes.draw do
  resources :users, :only => [:index, :show] do
    member do
      get 'venues'
    end
  end

  get  "landlord/index", :as => :dashboard
  get  "landlord/portfolio", :as => :portfolio
  get  "landlord/activity", :as => :activity
  post "landlord/sell/:id" => "landlord#sell", :as => :sell

  get  "account/index"
  get  "account/update"

  resources :venues do
    member do
      post 'buy'
    end
  end

  get "/account" => "account#index", :as => :account
  post "/account/update" => "account#update", :as => :update_account

  get "/welcome" => "sessions#welcome", :as => 'welcome'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'venues#index'

end

app/controllers/landlord_controller.rb
# TODO : use LandlordRequest

class LandlordController < ApplicationController
  before_filter :logged_in?

  require "net/https"
  require "uri"
  
  def index
    @uri = URI.parse("https://www.landlordgame.com/v2-1-0/getUserDetails.php")

    set_http()

    @request.set_form_data({
      "auth" => current_user.ll_auth,
      "userId" => current_user.ll_user_id
      })

    response = @http.request(@request)
    begin
      @json = JSON.parse(response.body)
      session[:bankBalance] = @json['bankBalance']
      session[:formattedNetWorth] = @json['formattedNetWorth']
      session[:coinsBalance] = @json['coinsBalance']
    rescue
      redirect_to "/account", :notice => "Please set you userId and auth token (hard to find)"
    end

  end

  def portfolio
    @uri = URI.parse("https://www.landlordgame.com/v2-1-0/getPortfolio.php")

    set_http()

    @request.set_form_data({
      "auth" => current_user.ll_auth,
      "userId" => current_user.ll_user_id
      })

    response = @http.request(@request)
    begin
      @json = JSON.parse(response.body)
    rescue
      redirect_to "/account", :notice => "Please set you userId and auth token (hard to find)"
    end

  end

  def activity
    @uri = URI.parse("https://www.landlordgame.com/v2-1-0/getActivity.php")

    set_http()

    @request.set_form_data({
      "auth" => current_user.ll_auth,
      "userId" => current_user.ll_user_id,
      "timezone" => "3600",
      "since" => Time.now.to_i - 80000
      })
    response = @http.request(@request)
    begin
      @json = JSON.parse(response.body)
    rescue
      redirect_to "/account", :notice => "Please set you userId and auth token (hard to find)"
    end
  end


  def sell
    @uri = URI.parse("https://www.landlordgame.com/v2-1-0/sellVenue.php")

    set_http()

    @request.set_form_data({
      "auth" => current_user.ll_auth,
      "userId" => current_user.ll_user_id,
      "venueId" => params[:id]
      })

    response = @http.request(@request)
    respond_to do |format|
      msg = response.body
      format.html { redirect_to portfolio_path, notice: "Msg : #{msg}" }
    end
  end

  protected

  def set_http
    @http = Net::HTTP.new(@uri.host, @uri.port)
    @http.use_ssl = true
    @http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    @request = Net::HTTP::Post.new(@uri.request_uri)
    @request.add_field 'Content-Type', 'application/x-www-form-urlencoded; charset=utf-8'
    @request.add_field 'X-Requested-With', 'XMLHttpRequest'
    @request.add_field 'Proxy-Connection', 'close'
    @request.add_field 'Accept-Encoding', 'gzip'
    @request.add_field 'User-Agent', 'Appcelerator Titanium/2.1.3.GA (iPhone/6.0.1; iPhone OS; fr_BE;)'
  end

end

app/helpers/landlord_helper.rb
module LandlordHelper
end

app/views/landlord/activity.html.erb
<h3>Activity</h3>
<table class="table">
	<% for item in @json['activity'] %>
	<% if item['type']=='earnedRent' %>
	<tr>
		<td>You <%= item['message'] -%></td>
		<td><%= item['dateStamp'] -%></td>
		<td></td>
		<td>+<%= df item['amount'] -%></td>
	</tr>
	<% end %>
	<% end %>
</table>

app/views/landlord/index.html.erb
<h3>Your Landlord</h3>

<table class="table">
	<tr>
		<td>Bank balance</td>
		<td><%= @json['bankBalance'] -%></td>
	</tr>
		<tr>
		<td>Coins balance</td>
		<td><%= @json['coinsBalance'] -%></td>
	</tr>
			<tr>
		<td>Net worth</td>
		<td><%= @json['formattedNetWorth'] -%></td>
	</tr>
</table>

app/views/landlord/portfolio.html.erb
<table id='sortit' class="tablesorter table table-hover">
	<thead>
		<tr>
			<th>Name</th>
			<th class="{sorter: 'digit'}">Ch</th>
			<th class="{sorter: 'digit'}">Up.</th>
			<th>Place</th>
			<th>Cat</th>
			<th class="{sorter: 'digit'}">Hours</th>
			<th class="{sorter: 'digit'}">Purchase</th>
			<th class="{sorter: 'digit'}">Current</th>
			<th class="{sorter: 'digit'}">#Ch</th>
			<th class="{sorter: 'percent'}">Return</th>
			<th class="{sorter: 'digit'}">Today</th>
			<th class="{sorter: 'digit'}">Total</th>
			<th class="{sorter: 'digit'}">M1</th>
			<th class="{sorter: 'digit'}">M2</th>
			<th class="{sorter: false}"></th>
		</tr>
	</thead>
	<% for item in @json %>
	<tr>
		<td><b><%= item['name'] -%></b>
		        <br />
   <%# item['items'].each do |el| %>
        <%# image_tag el['itemIcon'], :width => 20 -%>
        <%# end %></td>
		<td><%= sdf item['venueMetrics'][0]['value'] -%></td>
		<td><%= item['items'].size -%></td>
		<td><%= item['location']['city'] -%> <%= item['location']['country'] -%></td>
		<td><%= item['category']['name'] -%></td>
				<% hours = (Time.now.to_i - item['purchaseDate']) / 3600 %>
		<td><%= hours -%></td>
		<td><%= sdf item['purchasePrice'] -%></td>
		<td><%= df item['rawMarketValue'] -%></td>
		<td><%= item['checkins'] -%></td>
		<td><%= item['returnOnInvestment'] -%>%</td>
		<td><%= df item['newRent'] -%></td>
		<td><%= df item['earnings'] -%></td>
		<% if hours>0 %>
			<td><%= item['earnings'].to_i / hours -%></td>
			<td><%= item['earnings'].to_i * 10000 / hours / int(item['purchasePrice']) -%></td>
		<% else %>
			<td></td><td></td>
		<% end %>
		<td><%= link_to raw("<i class='icon-shopping-cart'></i>"), sell_path(item['venueId']), :method => :post -%></td>
	</tr>
	<% end %>

</table>
M1 : earnings / hour (higher is better) <br />
M2 : earnings / hour / purchasePrice * 10000 (higher is better)
<script type="text/javascript">
var myTextExtraction = function(node)
{
	return parseInt( node.innerHTML.replace(/\,/,'').replace(/\./,'').replace(/\s/,'') );
}


$(document).ready(function()
{
	$("#sortit").tablesorter(  );
}
);

</script>
<style type="text/css">
	.tablesorter td ,.tablesorter th {
		font-size: 12px;
		padding: 1px;
	}
</style>