config/routes.rb
Landlorder::Application.routes.draw do
  resources :users, :only => [:index, :show] do
    member do
      get 'venues'
    end
  end

  get  "landlord/index", :as => :dashboard
  get  "landlord/portfolio", :as => :portfolio
  get  "landlord/activity", :as => :activity
  post "landlord/sell/:id" => "landlord#sell", :as => :sell

  get  "account/index"
  get  "account/update"

  resources :venues do
    member do
      post 'buy'
    end
  end

  get "/account" => "account#index", :as => :account
  post "/account/update" => "account#update", :as => :update_account

  get "/welcome" => "sessions#welcome", :as => 'welcome'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'venues#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "Landlorder" %></title>
	<%= csrf_meta_tags %>

	<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->
      <%= javascript_include_tag "application" %>
      <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

  	<div class="navbar navbar-static-top">
  		<div class="navbar-inner">
  			<div class="container">
  				<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  				</a>
  				<a class="brand" href="/venues">Landlorder</a>
  				<div class="container nav-collapse">
  					<ul class="nav">
  						<li><%= link_to "Buy", "/venues"  %></li>
  						<li><%= link_to "Dashboard", "/landlord/index"  %></li>
  						<li><%= link_to "Activity", "/landlord/activity"  %></li>
  						<li><%= link_to "Portfolio", "/landlord/portfolio"  %></li>
  						<% if is_jedi? %>
						<li><%= link_to "Users", users_path  %></li>
  						<% end %>
</ul>
<a style="margin-top:9px;" href="https://foursquare.com/search" target="_blank" class="btn btn-mini btn-inverse">Search Foursquare</a>
<ul class="nav pull-right">
	<% if current_user %>
	<li><a href="<%= url_for account_path -%>"><%= current_user.nickname %></a></li>
	<li><%= link_to "Sign Out", signout_path %></li>
	<% else %>
	<li><%= link_to "Sign in with Foursquare", "/auth/foursquare" %></li>
	<% end %>
</ul>
</div><!--/.nav-collapse -->
</div>
</div>
</div>

<div class="secondbar">
	<div class="container">
		<div class="row">
			<div class="span6">
				Bank Balance: <%= session[:bankBalance] -%> 
				Coins Balance: <%= session[:coinsBalance] -%> 
			</div>
			<div class="span6" style="text-align:right">
				Net Worth: <%= session[:formattedNetWorth] -%> 
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="span12">
			<% flash.each do |name, msg| %>
			<div class="alert <%= name -%> alert-success" style="margin-top:5px">
				<a class="close" data-dismiss="alert">×</a>
				<%= msg -%>
			</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<%= yield %>
		</div>
	</div><!--/row-->
	<footer>
		<p>&copy; LandLorder 2013</p>
	</footer>

</div> <!-- /container -->
</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-53476-12']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>